### PR TITLE
A bunch of Fixes/Improvements

### PR DESCRIPTION
**Pull request by anabsolutesloth**
TagiaDusts.zs: IE Crusher would create ore from Dust, silly Adam :p corrected in this PR.
Harvestcraft.zs: Harvestcraft Garden/plant info, tell people to use the Farming for Blockheads market to get the seeds.
Immersive.zs: Alter Railgun and Revolver recipes in Normal mode to use a bunch of TechReborn parts and some IE parts to reflect their significant power boosts.
We may want to consider making Immersive.zs an all-modes script, just maybe.
Tooltip.zs: Change Revolver Bullet damage tooltip to state ~20x instead of ~50x.

UniDict.cfg: Remove the Iron Essence->Ingot recipe and the hilariously easy Steel recipes through this because CraftTweaker can't kill them, it's literally Iron and Coal in crafting, that's _too_ cheap.
tweakersconstruct.cfg: Removes the need for Decaster.zs by directly removing issue-causing traits, will send to bread incase he needs, and will also keep myself incase needed again.
Also gives Ice Dragonsteel parts some ok traits, cause they were in the list but unaffected. _Adam Grade Testing:tm:_
Rats.cfg: blacklist Rats from spawning in the Erebus, cause they spawn way too much in there.
rftools/dimensions.cfg: Sneaky Adam change that made dimension percentage power cost ludicrous and near unusable, also increase max RF/t/side rate for the Dimension Builder.
rftools.cfg: Make Shield Projector actually usable.

All of these things have been tested to ensure they work, except for the Railgun Power use change, i still advise testing them in your own instance.
NOTE 29/6/21: Most changes from rats.cfg and beyond HAVE NOT been tested.

### CODE REVIEW

**Comment by anabsolutesloth** [comment]
Railgun Recipe ingame
image
Item List: Top Left->Bottom Right
Superconductor Cable (TR) 3x, Wooden Grip (IE) 2x, Lapotronic Energy Orb (TR), Magnet (Powersuits), Revolver Barrel (IE) 2x.
UPDATE: Lapotronic Orb was swapped to HV Capacitor, and then EV Capacitor.

**Comment by criscky** [comment]
just a question the railgun, the middle one is a thing from techreborn, it needs to be fully empty, or it can have rf?

**Comment by anabsolutesloth** [comment]
> just a question the railgun, the middle one is a thing from techreborn, it needs to be fully empty, or it can have rf?

It is set to not have an NBT tag or metadata required in the recipe, i did not /mt hand it.
I will check if it is happy with ones in different states.
UPDATE: it does not accept a charged one :/
I'll see if i can somehow make it do that, if not, we can just use another expensive battery.

**Comment by criscky** [comment]
o
i read in their discord a thing
try put this
.withEmptyTag()
and see if you can use any value

**Comment by anabsolutesloth** [comment]
> o
> i read in their discord a thing
> try put this
> .withEmptyTag()
> and see if you can use any value

o, will try some other time, already replaced it with powersuits hv capacitor.

**Comment by adam9899** [comment]
approved

**Comment by cornehoskam** [comment]
@anabsolutesloth Let me know once the NBT recipe issue has been fixed! :)

**Comment by anabsolutesloth** [comment]
Oops i did a stupid when purging branches
@cornehoskam it is fixed already, i swapped the lapotronic orb for an HV Capacitor from powersuits.
There is another issue i need to resolve with MA first in the other PR tho, can't use Iron Essence no matter packmode, i can resolve that easily tho, will make commit soonly

**Comment by anabsolutesloth** [comment]
image
Revolver recipe ingame

**Comment by anabsolutesloth** [comment]
We should converse about whether to keep the preprocessor for normal mode Immersive.zs or not.

**Comment by Dagarath915** [comment]
The proposed rftools shield change will leave the tier4 shield generator capped at 6,250 blocks vs it's tooltip stated limit of 32,768 blocks. The input rf would need to be 2700000 to accommodate.

**Comment by criscky** [comment]
Emper just change the netherportalspread to what i changed in my PR "from Electroblob's"

**Comment by criscky** [comment]
@cornehoskam this PR prob need to analised and merged before the next update
i closed my PR #232 because emper makes the same change in this PR

**Comment by anabsolutesloth** [comment]
> Emper just change the netherportalspread to what i changed in my PR "from Electroblob's"

Pretty sure i basically did with https://github.com/Minecraft-Eternal/MC-Eternal-1.12/pull/183/commits/24828db5bd961ba52e383d6eeff840cd5541863a

**Comment by criscky** [comment]
my bad, i think i'm blind, and read the wrong config in the changes

**Comment by criscky** [comment]
Emper can you split this into small PRs?
I made one for the typos in the scripts in #232

**Comment by anabsolutesloth** [comment]
Way too much in one PR, and it is split into multiple now, so no longer needed, closing.

**Pull request closed without merging**
