### PR TITLE
Upgrade MysticalAgri.zs

### PR DESCRIPTION
**Pull request by anabsolutesloth**
Massive Upgrade to MysticalAgri.zs, contains easily expandable lists for seed material names and recipe names.

Depends on enabling Cow, Enderium, Creeper, Wood, and Pig seeds, will get mad otherwise.
Ghast and Nether Seeds will stay disabled by decision of Adam (check #mce-dev in the Discord), as will Experience Seeds.
Quest Files are not reshuffled in coordinates, so things will look a bit off in the tab, please correct that when testing.

PLEASE TEST THIS PR BEFORE MERGING.

### CODE REVIEW

**Comment by anabsolutesloth** [comment]
Oops i did a stupid
i was purging branches and yoted this and #183

**Comment by anabsolutesloth** [comment]
We should converse about whether or not Diamond, Gold, Blaze, and Netherstar seeds should be craftable in classic.

**Review by criscky — CHANGES_REQUESTED** [review]
ClassicModeThings.zs

in line 10 you're missing the ;
also in line 10, please put 
```var nocraftseeds as IItemStack[]```

you might or might not need put a import 
```import crafttweaker.item.IItemStack;```

**Comment by criscky** [comment]
~~about the unidict rood recipe, go to unidict config file and put this
`unidict:ingotiron_x6_shape.aaaa aaaa`
in "S:recipeToRemoveList"~~

i just saw you put that in another PR
:v

**Review by criscky — APPROVED** [review]

**Pull request merged**
