### PR TITLE
Nature's Aura questline

### PR DESCRIPTION
**Pull request by anabsolutesloth**
I was bored so i made this.
A quick runthrough of the basic progression of Nature's Aura and functionality of essential devices, aswell multiple instances of tell you to read the book, and exactly 2 memes.

### CODE REVIEW

**Comment by anabsolutesloth** [comment]
Did not give quests rewards, gonna put into Draft.

**Comment by anabsolutesloth** [comment]
Rewards added, mostly Coins, a few Common lootboxes, and a single Black Market container at the end.

**Review by adam9899 — APPROVED** [review]

**Review by criscky — APPROVED** [review]
i like that the quest form a leaf
🍃

**Comment by anabsolutesloth** [comment]
> i like that the quest form a leaf
> 🍃

glad you noticed that little detail :>

**Pull request merged**
