### PR TITLE
[Quests]Update to the AS/Taum

### PR DESCRIPTION
**Pull request by Flame1869**
update for the Questing branch

### CODE REVIEW

**Comment by anabsolutesloth** [comment]
An image would be nice to review the changes a bit more visually.

**Comment by Flame1869** [comment]
> An image would be nice to review the changes a bit more visually.

Ah yes, sorry.
I'll add it tomorrow (y)

**Comment by Flame1869** [comment]
screenshots of some changes; most of it is based on the feedback from the discord channel.

u01
u02
u03

**Comment by anabsolutesloth** [comment]
Thaumcraft line looks good 👍 
_Maybe_ having the Impetus Conductor quest require either the Thaumium or Voidmetal Caster's Gauntlets would be a good idea, since it needs to be attached to one of them in order for the player to be able to use it.
Also, make sure that all the Gauntlet quests ignore NBT, otherwise there may be issues with them being completed.

AS for the Astral Line, Resonating Wand quest is still needed, and maybe remove the Starlight Bucket quest and swap it for the Lightwell, which should probably gate the Starlight Altar.
Starmetal should also gate the Celestial Altar, as a bit of it is needed.
And maybe throw in the Starlight Infuser after the Celestial Altar, having it gate the Iridescent Altar, since Resonating Gems are needed for it.

**Comment by adam9899** [comment]
Approved

**Comment by cornehoskam** [comment]
Closed for the time being due to quest changes with upcoming packmode

**Pull request closed without merging**
