### PR TITLE
Buff Lategame Tinkers' Materials

### PR DESCRIPTION
**Pull request by anabsolutesloth**
I would suggest testing on full MCE, these stats were built in Lite and will be somewhat different here, if you want me to change something ping me in the discord.

### CODE REVIEW

**Comment by anabsolutesloth** [comment]
I'm going to extend this to some other materials aswell, notably Jade from Erebus, so i've put it into Draft mode.

**Comment by adam9899** [comment]
approved when complete

**Comment by anabsolutesloth** [comment]
@adam9899 Make sure you test it when i add the new Materials!

**Comment by anabsolutesloth** [comment]
Gonna make some changes again, so it's back into Draft mode.

**Pull request merged**
